
# Searching `DSECollection`s


## Finding unique values for each field of a `DSETriple`

The `CitablePhysicalText` package includes functions for querying a `DSECollection`.  We'll load a sample dataset from the file `test/assets/proclusdse.cex` in this github repository.

```{julia}
#| output: false
#| echo: false
#| warning: false
root = pwd() |> dirname |> dirname
```


```{julia}
using CitableBase
using CitablePhysicalText
f = joinpath(root, "test", "assets", "proclusdse.cex")
dsecollectionlist = fromcex(f, DSECollection, FileReader)
```

The result is a (possibly empty) Vector of `DSECollection`s.  This data set has a single collection, which we'll now work with.

```{julia}
dsecoll = dsecollectionlist[1]
```

You can find the unique list of URNs for each field of the collection's triples with the functions `surfaces`, `images` and `texts`.

```{julia}
surfaces(dsecoll)
```

The `images` function has an optional parameter defining whether or not to include subreferences.

```{julia}
images(dsecoll, keepsubref = false)
```



Similarly, the `passages` function has an optional parameter defining whether or not to include the passage component.

```{julia}
passages(dsecoll, keeppassage = false)
```


## Querying by field

The following functions find values for one field of a `DSETriple` filtered by another field.


Find all text passages on a given surface:

```{julia}
using CitableObject
page = Cite2Urn("urn:cite2:hmt:msA.v1:1r")
textsforsurface(page, dsecoll)
```


Find all text passages indexed to a given image:

```{julia}
img = Cite2Urn("urn:cite2:hmt:vaimg.2017a:VA001RN_0002")
textsforimage(img, dsecoll)
```

Find what pages a text occurs on:

```{julia}
using CitableText
homer = CtsUrn("urn:cts:greekLit:tlg4036.tlg023.va:Homer")
surfacesfortext(homer, dsecoll)
```

Find what images illustrate a text:

```{julia}
homer = CtsUrn("urn:cts:greekLit:tlg4036.tlg023.va:Homer")
imagesfortext(homer, dsecoll)
```

Find surfaces illustrated by an image:

```{julia}
surfacesforimage(img, dsecoll)
```


Find images illustrating a surface;

```{julia}
imagesforsurface(page, dsecoll)
```

